version: '3'

services:
  linuxdocker:
    image: linuxdocker
    container_name: linuxdocker
    expose:
      - "80"
    ports:
      - "5000:80"
    build:
      context: ./LinuxDocker
      dockerfile: Dockerfile

  windocker:
    image: windocker
    container_name: windocker
    ports:
      - "5001:80"
    links:
      - linuxdocker
    build:
      context: ./WinDocker
      dockerfile: Dockerfile
